name: CI

on:
  push:
  branches: [main] ubuntu
  pull_request:
  branches: [main]

  jobs:
    start:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
    uses: actions/checkout@v2

    -name: Run sample script
    uses: Hello, world
